/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pharmacy;

//import Business.Enterprise.Enterprise;
import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Order;
import Business.WorkQueue.VaccinatePatient;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nishigandha
 */
public class ManagePatientVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientVaccineJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    //Enterprise enterprise;
    public ManagePatientVaccineJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.city=city;
        this.organization=organization;
        //this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageInventory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccineVC = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        lblBatch = new javax.swing.JLabel();
        txtStaffIDVC = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageInventory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManageInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageInventory.setText("PATIENT VACCINATION DETAILS");
        add(lblManageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 510, -1));

        tblVaccineVC.setBackground(new java.awt.Color(214, 229, 244));
        tblVaccineVC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Staff ID"
            }
        ));
        jScrollPane1.setViewportView(tblVaccineVC);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 692, 181));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Create Details");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        lblBatch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblBatch.setText("Staff ID:");
        add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        txtStaffIDVC.setEditable(false);
        txtStaffIDVC.setBackground(new java.awt.Color(214, 229, 244));
        add(txtStaffIDVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 200, -1));

        btnRefresh1.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Refresh");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-online-pharmacy.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       try{
        for(WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList())  {
            VaccinatePatient vp = (VaccinatePatient)wr;
            vp.setStaff(userAccount);
           for(Patient p: vp.getNonVaccPatientList()){
               if(p.getVacStatus().equals("Partially Vaccinated")){
                   p.setVacStatus("Fully Vaccinated");
               }
                   else{
                           p.setVacStatus("Partially Vaccinated");
                           }
               }
           }
        txtStaffIDVC.setText(String.valueOf(userAccount.getEmployee().getId()));
        
        populateTable();
        JOptionPane.showMessageDialog(this, "All patients vaccinated");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "No Work request");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefresh1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblManageInventory;
    private javax.swing.JTable tblVaccineVC;
    private javax.swing.JTextField txtStaffIDVC;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblVaccineVC.getModel();
        dtm.setRowCount(0);

            
                for(WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList())  {
            VaccinatePatient vp = (VaccinatePatient)wr;
            vp.setStaff(userAccount);
           for(Patient p: vp.getNonVaccPatientList()){
                    
                    Object[] row = new Object[3];
                    row[0] = p.getPatientId();
                    row[1] = p.getPersonName();
                    row[2] = vp.getStaff().getEmployee().getId();
                    
                    dtm.addRow(row);
                
                }//To change body of generated methods, choose Tools | Templates.
                }
    }
}
