/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pharmacy;


import Business.City.City;
import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Nishigandha
 */

public class PharmacyAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccinationCenterAdminJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    //Enterprise enterprise;
    public PharmacyAdminJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.city=city;
        this.organization=organization;
        //this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewInventory = new javax.swing.JButton();
        btnManageStaff = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        lblManufacturereAdmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewInventory.setBackground(new java.awt.Color(0, 0, 0));
        btnViewInventory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInventory.setText("View Inventory");
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });
        add(btnViewInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 192, 30));

        btnManageStaff.setBackground(new java.awt.Color(0, 0, 0));
        btnManageStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStaff.setText("Manage Staff");
        btnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStaffActionPerformed(evt);
            }
        });
        add(btnManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 192, 30));

        btnPlaceOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 192, 30));

        lblManufacturereAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManufacturereAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturereAdmin.setText("PHARMACY ADMIN HOMEPAGE");
        add(lblManufacturereAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 988, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-online-pharmacy.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 70, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-vaccine.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
       ViewVaccineStorageJPanel viewVaccineInventoryJPanel = new ViewVaccineStorageJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("viewVaccineInventoryJPanel", viewVaccineInventoryJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next( userProcessContainer);
    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
       ManagePharmacyStaffJPanel manageVaccinationCenterStaffJPanel = new ManagePharmacyStaffJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("manageVaccinationCenterStaffJPanel", manageVaccinationCenterStaffJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next( userProcessContainer);
    }//GEN-LAST:event_btnManageStaffActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
       PlaceVaccineOrderJPanel placeVaccineOrderJPanel = new PlaceVaccineOrderJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("placeVaccineOrderJPanel", placeVaccineOrderJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next( userProcessContainer);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblManufacturereAdmin;
    // End of variables declaration//GEN-END:variables
}
