/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author Nishigandha
 */
public class splashscreen extends javax.swing.JFrame {

    /**
     * Creates new form splashscreen
     */
    public splashscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoadingprogress = new javax.swing.JProgressBar();
        btnLoadNo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoadingprogress.setForeground(new java.awt.Color(255, 255, 51));
        lblLoadingprogress.setBorderPainted(false);
        lblLoadingprogress.setFocusable(false);
        lblLoadingprogress.setRequestFocusEnabled(false);
        lblLoadingprogress.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblLoadingprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1600, 40));

        btnLoadNo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnLoadNo.setForeground(new java.awt.Color(255, 255, 153));
        btnLoadNo.setText("99%");
        jPanel1.add(btnLoadNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        lblTitle.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(225, 255, 255));
        lblTitle.setText("Patient Shelter");
        lblTitle.setToolTipText("");
        lblTitle.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 500, -1));

        lblLoading.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 153));
        lblLoading.setText("Loading ...");
        lblLoading.setToolTipText("");
        jPanel1.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 410, -1));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-patientCare.png"))); // NOI18N
        lblIcon.setToolTipText("");
        jPanel1.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, 70, 60));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-covid-test.png"))); // NOI18N
        jPanel1.add(lblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                 MainJFrame main = new MainJFrame();
                 splashscreen sc =new splashscreen();
                 sc.setVisible(true);
              
//       try {
//            for (int row =0;row<=100;row++) {
//                Thread.sleep(40);
//                sc.loadingnumber.setText(Integer.toString(row)+"%");
//                sc.loadingprogress.setValue(row);
//                System.out.println(row);
//                if (row == 100) {
//                    
//                    sc.setVisible(false);
//                    main.setVisible(true);
//                }
//            }
//        } catch (Exception e) {
//        } 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnLoadNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblLoading;
    public javax.swing.JProgressBar lblLoadingprogress;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
