/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Laboratory;

import Business.EcoSystem;
import Business.Person.Person;
import Business.LabReport.LabReport;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nishigandha
 */
public class ManageTestManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTestReportsJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    public ManageTestManagerJPanel(EcoSystem system, JPanel userProcessContainer) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personTestTableS = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearchS = new javax.swing.JTextField();
        lblSearchT = new javax.swing.JLabel();
        lblManagePatient = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personTestTableS.setBackground(new java.awt.Color(214, 229, 244));
        personTestTableS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Report"
            }
        ));
        jScrollPane1.setViewportView(personTestTableS);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 855, 183));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        txtSearchS.setBackground(new java.awt.Color(214, 229, 244));
        add(txtSearchS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 220, -1));

        lblSearchT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchT.setText("Person Name:");
        add(lblSearchT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        lblManagePatient.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManagePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagePatient.setText("TEST MANAGER");
        add(lblManagePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 740, -1));

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH TABLES");
        btnRefresh.setBorder(new javax.swing.border.MatteBorder(null));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 110, 25));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-covid-test.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/4.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search = txtSearchS.getText();
        
        DefaultTableModel dtm = (DefaultTableModel) personTestTableS.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[4];
        for(Person person: system.getPersonDirectory().getPersonList()){
//            System.out.println(person);
            if(person.getPersonName().equals(search)){
                ArrayList<LabReport> testReports = person.getTestHistory().getTestReportList();
            for(LabReport report: testReports){
                row[0] = person.getPersonID();
                row[1] = person.getPersonName();
                row[2] = report.isResult();
                dtm.addRow(row);
            }
            
            
            }
            
           
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TestingLabAdminJPanel sysAdminwjp = (TestingLabAdminJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManagePatient;
    private javax.swing.JLabel lblSearchT;
    private javax.swing.JTable personTestTableS;
    private javax.swing.JTextField txtSearchS;
    // End of variables declaration//GEN-END:variables
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) personTestTableS.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[4];
        for(Person person: system.getPersonDirectory().getPersonList()){
//            System.out.println(person);
                ArrayList<LabReport> testReports = person.getTestHistory().getTestReportList();
            for(LabReport report: testReports){
                row[0] = person.getPersonID();
                row[1] = person.getPersonName();
                row[2] = report.isResult();
                dtm.addRow(row);
            }
            
            
            
            
           
        }
    }

}
