/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Laboratory;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nishigandha
 */
public class TestingLabAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestingLabAdminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    public TestingLabAdminJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.city=city;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageReport = new javax.swing.JButton();
        lblManufacturereAdmin = new javax.swing.JLabel();
        btnNewReport = new javax.swing.JButton();
        btnManageTestT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageReport.setBackground(new java.awt.Color(0, 0, 0));
        btnManageReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageReport.setForeground(new java.awt.Color(255, 255, 255));
        btnManageReport.setText("Manage Test Reports Data");
        btnManageReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReportActionPerformed(evt);
            }
        });
        add(btnManageReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 230, 30));

        lblManufacturereAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManufacturereAdmin.setForeground(new java.awt.Color(51, 51, 51));
        lblManufacturereAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturereAdmin.setText("TESTING LAB ADMIN HOMEPAGE");
        add(lblManufacturereAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 680, -1));

        btnNewReport.setBackground(new java.awt.Color(0, 0, 0));
        btnNewReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewReport.setForeground(new java.awt.Color(255, 255, 255));
        btnNewReport.setText("New Report");
        btnNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReportActionPerformed(evt);
            }
        });
        add(btnNewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 230, 30));

        btnManageTestT.setBackground(new java.awt.Color(0, 0, 0));
        btnManageTestT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageTestT.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTestT.setText("Manage Requested Tests");
        btnManageTestT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTestTActionPerformed(evt);
            }
        });
        add(btnManageTestT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-covid-test.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/4.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReportActionPerformed
        // TODO add your handling code here:
        ManageTestManagerJPanel manageTestReportsJPanel = new ManageTestManagerJPanel(system, userProcessContainer);
        userProcessContainer.add("manageTestReportsJPanel", manageTestReportsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageReportActionPerformed

    private void btnNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReportActionPerformed
        // TODO add your handling code here:
        NewReportJPanel newReportJPanel = new NewReportJPanel(system, userProcessContainer);
        userProcessContainer.add("newReportJPanel", newReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewReportActionPerformed

    private void btnManageTestTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTestTActionPerformed
        // TODO add your handling code here:
        ManageScheduledTestsJPanel manageScheduledTestReports = new ManageScheduledTestsJPanel(userProcessContainer, system, enterprise);
        userProcessContainer.add("manageScheduledTestReports", manageScheduledTestReports );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTestTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageReport;
    private javax.swing.JButton btnManageTestT;
    private javax.swing.JButton btnNewReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblManufacturereAdmin;
    // End of variables declaration//GEN-END:variables
}
