/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.VaccineProvider;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.VaccineProvider;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.Vaccine.VaccineDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nishigandha
 */
public class ManageStorageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    //VaccineManufacturer e =(VaccineManufacturer)enterprise;
    public ManageStorageJPanel(JPanel userProcessContainer,City city,UserAccount userAccount,Organization organization,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.userAccount=userAccount;
        this.city=city;
        this.organization=organization;
        this.enterprise=enterprise;
        //VaccineManufacturer e =(VaccineManufacturer)enterprise;
        populateTable();
    }
    //VaccineManufacturer e =(VaccineManufacturer)enterprise;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagestore = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccineStorage = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblBatch = new javax.swing.JLabel();
        txtBatchNoVp = new javax.swing.JTextField();
        txtQuantityVP = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtStatusVP = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNameVP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManagestore.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManagestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagestore.setText("MANAGE VACCINE STORAGE");
        add(lblManagestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 620, -1));

        lblAvailability.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAvailability.setText("Available Vaccine Stock:");
        add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        txtSize.setBackground(new java.awt.Color(214, 229, 244));
        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });
        add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 220, -1));

        tblVaccineStorage.setBackground(new java.awt.Color(214, 229, 244));
        tblVaccineStorage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Batch Number", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblVaccineStorage);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 951, 181));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Stock");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, -1, -1));

        lblBatch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblBatch.setText("Batch No:");
        add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        txtBatchNoVp.setBackground(new java.awt.Color(214, 229, 244));
        add(txtBatchNoVp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 200, -1));

        txtQuantityVP.setBackground(new java.awt.Color(214, 229, 244));
        add(txtQuantityVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 200, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblQuantity.setText("Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, -1));

        txtStatusVP.setBackground(new java.awt.Color(214, 229, 244));
        txtStatusVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusVPActionPerformed(evt);
            }
        });
        add(txtStatusVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 200, -1));

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblStatus.setText("Status:");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Stock");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, -1, -1));

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        txtNameVP.setBackground(new java.awt.Color(214, 229, 244));
        add(txtNameVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 200, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-vaccine.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/5.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
         int qty;
         int batchId;
         String status;
         String name;
         qty = Integer.parseInt(txtQuantityVP.getText());
         batchId = Integer.parseInt(txtBatchNoVp.getText());
         status = txtStatusVP.getText();
         name = txtNameVP.getText();
         VaccineProvider e =(VaccineProvider)enterprise;
         System.out.println(e.getVaccineDirectory().getVaccDir());
         Vaccine v = e.getVaccineDirectory().addVaccDir(qty, batchId, status, name);
         /*v.setBatchId(batchId);
         v.setName(name);
         v.setQty(qty);
         v.setStatus(status);*/
         populateTable();
         
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VaccineProvider e =(VaccineProvider)enterprise;
        int count = 0;
        for(Vaccine vaccine: e.getVaccineDirectory().getVaccDir()){
          count = count+vaccine.getQuantity();
        }
        txtSize.setText(String.valueOf(count));
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectRow = tblVaccineStorage.getSelectedRow();
        //VaccineManufacturer e =(VaccineManufacturer)enterprise;
        if(selectRow>=0){
            String name= (String) tblVaccineStorage.getValueAt(selectRow, 0);
            int BatchID= (int) tblVaccineStorage.getValueAt(selectRow, 1);
            int Quantity = (int) tblVaccineStorage.getValueAt(selectRow, 2);
            String status= (String) tblVaccineStorage.getValueAt(selectRow, 3);
            
            txtNameVP.setText(name);
            txtBatchNoVp.setText(String.valueOf(BatchID));
            txtQuantityVP.setText(String.valueOf(Quantity));
            txtStatusVP.setText(status);
        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        VaccineProvider e =(VaccineProvider)enterprise;
        int qty=Integer.parseInt(txtQuantityVP.getText());
        int batchId=Integer.parseInt(txtBatchNoVp.getText());
        String status=txtStatusVP.getText();
        String name=txtNameVP.getText();
        
        for(Vaccine v: e.getVaccineDirectory().getVaccDir()){
            if(v.getBatchNo()==batchId){
                v.setVacName(name);
                v.setQuantity(qty);
                v.setVacStatus(status);
            }
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        VaccineProvider e =(VaccineProvider)enterprise;
        int batchId=Integer.parseInt(txtBatchNoVp.getText());
        for(Vaccine v: e.getVaccineDirectory().getVaccDir()){
            if(v.getBatchNo()==batchId){
                e.getVaccineDirectory().getVaccDir().remove(v);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineProviderAdminJPanel manageOrderjp = (VaccineProviderAdminJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtStatusVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusVPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusVPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblManagestore;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblVaccineStorage;
    private javax.swing.JTextField txtBatchNoVp;
    private javax.swing.JTextField txtNameVP;
    private javax.swing.JTextField txtQuantityVP;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtStatusVP;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
         DefaultTableModel dtm = (DefaultTableModel) tblVaccineStorage.getModel();
        dtm.setRowCount(0);

                VaccineProvider vm =(VaccineProvider)enterprise;
                for (Vaccine vaccine : vm.getVaccineDirectory().getVaccDir()) {
                    
                    Object[] row = new Object[4];
                    row[0] = vaccine.getVacName();
                    row[1] = vaccine.getBatchNo();
                    row[2] = vaccine.getQuantity();
                    row[3] = vaccine.getVacStatus();
                   
                   

                    dtm.addRow(row);
                
                } //To change body of generated methods, choose Tools | Templates.
    }
}
