/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineProvider;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nishigandha
 */
public class VaccineProviderAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineManufacturerAdminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    //Enterprise enterprise;
    public VaccineProviderAdminJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.userAccount=userAccount;
        this.city=city;
        this.organization=organization;
        this.enterprise=enterprise;
        //this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageStorage = new javax.swing.JButton();
        btnManageDeliveryManger = new javax.swing.JButton();
        lblManufacturereAdmin = new javax.swing.JLabel();
        btnManageOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageStorage.setBackground(new java.awt.Color(0, 0, 0));
        btnManageStorage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageStorage.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStorage.setText("Manage Storage");
        btnManageStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStorageActionPerformed(evt);
            }
        });
        add(btnManageStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 181, 30));

        btnManageDeliveryManger.setBackground(new java.awt.Color(0, 0, 0));
        btnManageDeliveryManger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageDeliveryManger.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDeliveryManger.setText("Manage Delivery Staff");
        btnManageDeliveryManger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveryMangerActionPerformed(evt);
            }
        });
        add(btnManageDeliveryManger, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 180, 30));

        lblManufacturereAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblManufacturereAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturereAdmin.setText("VACCINE PROVIDER HOMEPAGE");
        add(lblManufacturereAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 730, -1));

        btnManageOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrder.setText("Manage Orders");
        btnManageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderActionPerformed(evt);
            }
        });
        add(btnManageOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 181, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-vaccine.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/5.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStorageActionPerformed
       ManageStorageJPanel manageInventoryJPanel = new ManageStorageJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("manageInventoryJPanel", manageInventoryJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStorageActionPerformed

    private void btnManageDeliveryMangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveryMangerActionPerformed
       ManageDeliveryStaffJPanel manageDeliveryJPanel = new ManageDeliveryStaffJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("manageDeliveryJPanel", manageDeliveryJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliveryMangerActionPerformed

    private void btnManageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderActionPerformed
       ManageOrdersJPanel manageOrderJPanel = new ManageOrdersJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
       userProcessContainer.add("manageOrderJPanel", manageOrderJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDeliveryManger;
    private javax.swing.JButton btnManageOrder;
    private javax.swing.JButton btnManageStorage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblManufacturereAdmin;
    // End of variables declaration//GEN-END:variables
}
