/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Hospital;
import Business.Enterprise.Hospital;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Nishigandha
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    public HospitalAdminJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.city=city;
        this.organization=organization;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMDoctor = new javax.swing.JButton();
        btnMPatient = new javax.swing.JButton();
        btnMStaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMReqVaccine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(99, 221, 221));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMDoctor.setBackground(new java.awt.Color(0, 0, 0));
        btnMDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnMDoctor.setText("Manage Doctor");
        btnMDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDoctorActionPerformed(evt);
            }
        });
        add(btnMDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 230, 30));

        btnMPatient.setBackground(new java.awt.Color(0, 0, 0));
        btnMPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnMPatient.setText("Manage Patient");
        btnMPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPatientActionPerformed(evt);
            }
        });
        add(btnMPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 230, 30));

        btnMStaff.setBackground(new java.awt.Color(0, 0, 0));
        btnMStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnMStaff.setText("Manage Staff");
        btnMStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMStaffActionPerformed(evt);
            }
        });
        add(btnMStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 230, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOSPITAL ADMIN HOMEPAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 48, 1210, -1));

        btnMReqVaccine.setBackground(new java.awt.Color(0, 0, 0));
        btnMReqVaccine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMReqVaccine.setForeground(new java.awt.Color(255, 255, 255));
        btnMReqVaccine.setText("Generate Request For Non-Vaccinated People");
        btnMReqVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMReqVaccineActionPerformed(evt);
            }
        });
        add(btnMReqVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 310, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/icons-hospital.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/5.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1930, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDoctorActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel manageDoctorJPanel = new ManageDoctorJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
        userProcessContainer.add("manageDoctorJPanel", manageDoctorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMDoctorActionPerformed

    private void btnMPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPatientActionPerformed
        // TODO add your handling code here:
        ManagePatientJPanel managePatientJPanel = new ManagePatientJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
        userProcessContainer.add("managePatientJPanel", managePatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMPatientActionPerformed

    private void btnMStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMStaffActionPerformed
        // TODO add your handling code here:
        ManageHospitalStaffJPanel manageStaffJPanel = new ManageHospitalStaffJPanel(userProcessContainer, city, userAccount, organization, enterprise, system);
        userProcessContainer.add("manageStaffJPanel", manageStaffJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMStaffActionPerformed

    private void btnMReqVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMReqVaccineActionPerformed
        ManageVaccinationRequest pr = new ManageVaccinationRequest(userProcessContainer, city, userAccount, organization, enterprise, system);
        userProcessContainer.add("pr", pr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMReqVaccineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMDoctor;
    private javax.swing.JButton btnMPatient;
    private javax.swing.JButton btnMReqVaccine;
    private javax.swing.JButton btnMStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
